/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clasificadorjson;

import java.awt.Rectangle;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sinuhe
 */
public class Inicio extends javax.swing.JFrame {
 int indice;
 JLabel j1[];
 String salida="";
 int contadorasign;
 int contadorasign2;
 int contifs;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    
          contadorasign=0;
          contadorasign2=0;
          contifs=0;
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Asignacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("ENTRADAS PARA EL GENERADOR DE JSON");

        jButton3.setText("Objeto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Decision");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Atributo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("CODIGO PARA EL GENERADOR EN PROLOG");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clasificadorjson/imag.jpg"))); // NOI18N

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Listo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)
                        .addGap(67, 67, 67)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String name = JOptionPane.showInputDialog("Nombre de la variable: ");
       String val = JOptionPane.showInputDialog("Valor de la variable: ");
       salida=salida+"\nasignacion.\n"+name+".\n"+val+".";
        jTextArea1.setText("");
        jTextArea1.append(salida);
       String[] options = {"SI","NO"};
        String n = (String)JOptionPane.showInputDialog(null, "Elige opcion: ","DESEA HACER OTRA ASIGNACION?", JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(n.equals("SI")){jButton1.doClick(500);}
        if(n.equals("NO")){}
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String name = JOptionPane.showInputDialog("Nombre del objeto: ");
        if(contadorasign2==0){
        salida=salida+"\nobjeto.\n"+name+".";
        
        }
        else{
           /* if(contifs==0&&contadorasign2>0){
            salida=salida+"\nfin.\nobjeto.\n"+name+".";
            }
            else{*/
            salida=salida+"\nfin.\nobjeto.\n"+name+".";
           /* }*/
        }
       
        jTextArea1.setText("");
        jTextArea1.append(salida);
        
         String[] options = {"Metodo","numero","cadena"};
        String v = (String)JOptionPane.showInputDialog(null, "Elige opcion : ","Opcion Atributo", JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(v.equals("Metodo")){
            if(contadorasign2==0){
            salida=salida+"\nmetodo.";
       jTextArea1.setText("");
        jTextArea1.append(salida);
          String[] optionsa = {"asignacion","decision"};
        String va = (String)JOptionPane.showInputDialog(null, "Elige opcion : ","Opcion Metodo", JOptionPane.QUESTION_MESSAGE, null, optionsa, optionsa[0]);
        
        if(va.equals("asignacion")){jButton1.doClick(500);}
        if(va.equals("decision")){jButton4.doClick(500);}
            }
            else{
                String namex = JOptionPane.showInputDialog("Nombre del metodo: ");
                         salida=salida+"\n"+namex+".\nmetodo.";
       jTextArea1.setText("");
        jTextArea1.append(salida);
          String[] optionsa = {"asignacion","decision"};
        String va = (String)JOptionPane.showInputDialog(null, "Elige opcion : ","Opcion Metodo", JOptionPane.QUESTION_MESSAGE, null, optionsa, optionsa[0]);
        
        if(va.equals("asignacion")){jButton1.doClick(500);}
        if(va.equals("decision")){jButton4.doClick(500);}  
            }
        }
        
        if(v.equals("numero")){
            String name2 = JOptionPane.showInputDialog("Nombre del atributo: ");
            String val = JOptionPane.showInputDialog("Valor del atributo: ");
        salida=salida+"\n"+name2+".\nnumero.\n"+val+".";
       jTextArea1.setText("");
        jTextArea1.append(salida);}
        
        if(v.equals("cadena")){
            String name2 = JOptionPane.showInputDialog("Nombre del atributo: ");
            String val = JOptionPane.showInputDialog("Valor del atributo: ");
        salida=salida+"\n"+name2+".\ncadena.\n"+val+".";
       jTextArea1.setText("");
        jTextArea1.append(salida);}
          
       contadorasign2++;
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
          
        
       jTextArea1.setText("");
        jTextArea1.append(salida);
        String c = JOptionPane.showInputDialog("Condicion: ");
       
        /*if(contadorasign<1){*/
            salida=salida+"\ndecision.\n"+c+".";
       /* }
        else{
            salida=salida+"\nfin.\ndecision.\n"+c+".";
        }*/
        contadorasign++; 
        
        String[] options = {"Decision","Asignacion"};
        String n = (String)JOptionPane.showInputDialog(null, "Elige opcion: ","Verdadero", JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(n.equals("Decision")){
        jButton4.doClick(500);}
        if(n.equals("Asignacion")){jButton1.doClick(500);}
        
        
        String[] options22 = {"Decision","Asignacion","Finalizar"};
        String n2 = (String)JOptionPane.showInputDialog(null, "Elige opcion: ","Falso", JOptionPane.QUESTION_MESSAGE, null, options22, options22[0]);
        if(n2.equals("Decision")){salida=salida+"\nfin."; 
            jTextArea1.setText("");
        jTextArea1.append(salida);
            jButton4.doClick(500);}
        
        if(n2.equals("Asignacion")){
            salida=salida+"\nfin."; 
            jTextArea1.setText("");
        jTextArea1.append(salida);
            jButton1.doClick(500);}
        
          if(n2.equals("Finalizar")){
            jTextArea1.setText("");
        jTextArea1.append(salida);
           }
          contifs++;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String[] options = {"numero","cadena"};
        String v = (String)JOptionPane.showInputDialog(null, "Elige opcion : ","Opcion Atributo", JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        
        
        if(v.equals("numero")){
            String name2 = JOptionPane.showInputDialog("Nombre del atributo: ");
            String val = JOptionPane.showInputDialog("Valor del atributo: ");
        salida=salida+"\natrib.\n"+name2+".\nnumero.\n"+val+".";
       jTextArea1.setText("");
        jTextArea1.append(salida);}
        
        if(v.equals("cadena")){
            String name2 = JOptionPane.showInputDialog("Nombre del atributo: ");
            String val = JOptionPane.showInputDialog("Valor del atributo: ");
        salida=salida+"\natrib.\n"+name2+".\ncadena.\n"+val+".";
       jTextArea1.setText("");
        jTextArea1.append(salida);}
        
        
        
         
       
        
     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextArea1.setText("");
        salida="";
        contadorasign=0;
          contadorasign2=0;
          contifs=0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Controlador con=new Controlador(salida);
        con.inicio();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
